---
title: "week15"
output: html_notebook
---

## 5.2

```{r}
dataSet3 <-
  data.frame(
    dates = c("2016-11-15", NA, NA, "1997-05-07", "1995-08-25", "2002-09-20", NA, NA, NA, "1995-07-16", "2011-06-22"),
    grades = c(29, 53, 26, 27, 55, 69, NA, NA, 63, NA, 56),
    genders = c("Male", "Female", "Male", "Male", "Female", "Female", NA, "Male", "Male", "Female", "Female"),
    majors = c("economics", "economics", NA, "economics", "economics", "economics", "economics", "statistics", "law", "economics", "law")
  )
check_class() # function call
check_na()
```

```{r}
dataSet4 = data.frame(
  x = c(6,10,10,6,10,6,NA,NA,3,7),
  y = c(2,3,6,6,8,2,8,6,8,3)
)
```

```{r check-fun}
check_class <- function(){
  # class check
  class_check <- vector("integer", length(dataSet3))
  for(.x in seq_along(dataSet3)){
    class_check[[.x]] <- class(dataSet3[[.x]])
  }
  names(class_check) <- names(dataSet3)
  class_check # the last executed line
}


check_na <- function(){
  # NA check
  na_check <- vector("integer", length(dataSet3))
  for(.x in seq_along(dataSet3)){
    na_check[[.x]] <- sum(is.na(dataSet3[[.x]]))
  }
  names(na_check) <- names(dataSet3)
  na_check # the last executed line
}
```

### 5.2.3 Environments

```{r}
x = 1
y = 33

robot1 <- function(){
  x+y
  browser() # a stopping point
}
```

```{r}
robot1()
```

```{r}
x=c("b", "b", "b")
{
  x[[1]] <- "a"
}

print(x)
```

```{r}
change_x_1stValue2a <- function(){
  x[[1]] <- "a"
}

x=c("b", "b", "b")
change_x_1stValue2a() # the copy of x in execution environment is changed
x # source x is unchanged
```

```{r}
change_x_1stValue2a <- function(){
  x[[[1]] <- "a"
  return(x)
}

x=c("b", "b", "b")
x=change_x_1stValue2a()
x
```

```{r}
x=c("b", "b", "b")

change_x_1stValue2a <- function(){
  x[[1]] <- "a"
  x # or return(x)
}

x_new <- change_x_1stValue2a()
x <- x_new
x
```

### 5.2.4 Input arguments

```{r}
x = 1
y = 33
```

```{r}
robot1 <- function(){
  x+y
  # browser()
  return(x+y)
}
```

```{r}
robot2 <- function(x){
  x+y
  # browser()
  return(x+y)
}
```

```{r}
robot1()
```

```{r}
robot2(x=2)

robot2(x=20)

x
```

```{r}
x=1
robot1()
robot2(x=2)

x="a"
robot1()
robot2(x=3)
```

```{r}
dataSet3 <-
  data.frame(
    dates = c("2016-11-15", NA, NA, "1997-05-07", "1995-08-25", "2002-09-20", NA, NA, NA, "1995-07-16", "2011-06-22"),
    grades = c(29, 53, 26, 27, 55, 69, NA, NA, 63, NA, 56),
    genders = c("Male", "Female", "Male", "Male", "Female", "Female", NA, "Male", "Male", "Female", "Female"),
    majors = c("economics", "economics", NA, "economics", "economics", "economics", "economics", "statistics", "law", "economics", "law")
  )
check_class() # function call
check_na()
```

```{r}
dataSet4 = data.frame(
  x = c(6,10,10,6,10,6,NA,NA,3,7),
  y = c(2,3,6,6,8,2,8,6,8,3)
)
```

```{r}
check_class <- function(dataSet3){
  # class check
  class_check <- vector("integer", length(dataSet3))
  for(.x in seq_along(dataSet3)){
    class_check[[.x]] <- class(dataSet3[[.x]])
  }
  names(class_check) <- names(dataSet3)
  class_check # the last executed line
}
```

```{r}
check_class(dataSet3 = dataSet4)
```

```{r}
myfun <- function(x){
  x+y -> z
  z**2+6
}
```

* x is created inside robot's office.

* y copied/imported from the global environment lobby.

* z by product

```{r}
myfun(3)
```

```{r}
y=5
myfun(3)
```

```{r}
myfun <- function() return(xx+5) # shortcut definition

myfun <- function(){
  return(xx+5)
}

# forget myfun needs to import xx
myfun()

xx=c(1, 2)
myfun()

# there is a xx totally for different purpose
xx=c("a", "b")
myfun()
```

```{r}
list_string = list(c("a b", "cd "), c("  a", " b"))
for(.x in seq_along(list_string)){
  stringr::str_remove_all(list_string[[.x]], '\\s') -> 
    list_string[[.x]]
}
list_string
```

```{r}
remove_spaceInAlistChr <- function(list_string) {
  for(.x in seq_along(list_string)){
    stringr::str_remove_all(list_string[[.x]], '\\s') -> 
      list_string[[.x]]
  }
  list_string
}
```

```{r}
list_string = list(c("a b", "cd "), c("  a", " b"))

remove_spaceInAlistChr(list_string = list_string)
```

```{r}
myfun2 <- function(x, y, z) x+y+z
```

```{r}
myfun2(x=1, y=2, z=3)
myfun2(1, 2, 3) # ignore argument names if the order is correct
myfun2(z=3, x=1, y=2) # keep argument names can avoid wrong order problem
```

```{r}
string = c("a, b", "a, c, b")
{
  stringr::str_split(string, ", ") -> string_splited
  table(unlist(string_splited))
}
```

```{r}
tabulate_multipleSelections <- function(string){
  stringr::str_split(string, ", ") -> string_splited
  return(table(unlist(string_splited)))
}
c("a, b", "a, c, b") |> tabulate_multipleSelections()
hobby = c(
  'sport, reading, movie',
  'sport',
  'movie, sport, reading',
  'movie, Reading',
  'sport')
hobby |> tabulate_multipleSelections()
```

```{r}
hobby2 = c(
  'sport; reading; movie',
  'sport',
  'movie; sport; reading',
  'movie; Reading',
  'sport')
```

```{r}
tabulate_multipleSelections2 <- function(string, sep=","){
  pattern = paste(sep, '')
  stringr::str_split(string, pattern) -> string_splited
  table(unlist(string_splited))
}
```

```{r}
hobby |> tabulate_multipleSelections2()
hobby2 |> tabulate_multipleSelections2(sep=";") # or
# tabulate_multipleSelections2(hobby2, sep=";")
```